### ISSUE TITLE
The canvas has been tainted by cross-origin data.

### ISSUE THREAD

**Issue by moshsh** [shreyasbhat0/Thanos-Snap-Effect#1]
Hey are you still up for working on this? I downloaded the files, opened the index.html and can see Thanos and the snap button, I click the snap button but nothing happens. In my browser console I can see this error:

Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at file:///Thanos-Snap-Effect-master/index.html:31:29

**Comment by shreyasbhat0** [comment]
Hi Its been a while i haven't worked on this . 
Try to add allow cross-origin to the header . this will resolve your issue . 
For dev purpose you can still use live server where this works flawlessly
